Amend gha

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -2,111 +2,149 @@ name: Backend CI
 
 on:
   workflow_call:
-  workflow_dispatch:
+    inputs:
+      base-tag:
+        required: true
+        type: string
+      image-name-prefix:
+        required: true
+        type: string
+      image-name-suffix:
+        required: true
+        type: string
+      python-version:
+        required: true
+        type: string
+      plone-version:
+        required: true
+        type: string
 
-env:
-  IMAGE_NAME_PREFIX: ghcr.io/sneridagh/sneridagh-dev
-  IMAGE_NAME_SUFFIX: backend
-  PYTHON_VERSION: "3.11"
+defaults:
+  run:
+    working-directory: backend
 
 jobs:
 
-  meta:
-    runs-on: ubuntu-latest
-    outputs:
-      PLONE_VERSION: ${{ steps.vars.outputs.PLONE_VERSION }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Set Env Vars
-        id: vars
-        run: |
-          echo "PLONE_VERSION=$(cat backend/version.txt)" >> $GITHUB_OUTPUT
-
-  black:
+  lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
 
-      - name: Run check
-        uses: plone/code-analysis-action@v2
-        with:
-          base_dir: 'backend'
-          check: 'black'
+        - name: Checkout
+          uses: actions/checkout@v4
 
-  flake8:
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: true
+
+        - name: Check formatting
+          if: ${{ success() || failure() }}
+          id: ruff-format
+          run: uvx ruff@latest format --diff
+
+        - name: Check lint
+          if: ${{ success() || failure() }}
+          id: ruff-lint
+          run: uvx ruff@latest check --diff
+
+        - name: Check XML / ZCML
+          if: ${{ success() || failure() }}
+          id: zpretty
+          run: uvx zpretty@latest --check src
+
+        - name: Check Package Metadata
+          if: ${{ success() || failure() }}
+          id: pyroma
+          run: uvx pyroma@latest -d .
+
+        - name: Check Python Versions
+          if: ${{ success() || failure() }}
+          id: py-versions
+          run: uvx check-python-versions@latest .
+
+        - name: Report
+          if: ${{ success() || failure() }}
+          run: |
+            echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+            echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+            echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+            echo '| Format | ${{ steps.ruff-format.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Lint | ${{ steps.ruff-lint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| XML / ZCML | ${{ steps.zpretty.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Package Metadata | ${{ steps.pyroma.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+            echo '| Python Versions | ${{ steps.py-versions.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+
+  test:
     runs-on: ubuntu-latest
+    env:
+      PYTHON_VERSION: ${{ inputs.python-version }}
+      PLONE_VERSION: ${{ inputs.plone-version }}
     steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
 
-      - name: Run check
-        uses: plone/code-analysis-action@v2
-        with:
-          base_dir: 'backend'
-          check: 'flake8'
+        - name: Checkout
+          uses: actions/checkout@v4
 
-  isort:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: false
 
-      - name: Run check
-        uses: plone/code-analysis-action@v2
-        with:
-          base_dir: 'backend'
-          check: 'isort'
+        - name: Restore uv cache
+          uses: actions/cache@v4
+          with:
+            path: ${{ env.UV_CACHE_DIR }}
+            key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
+            restore-keys: |
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}
 
-  zpretty:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v4
+        - name: Install Plone and package
+          run: make install
 
-      - name: Run check
-        uses: plone/code-analysis-action@v2
-        with:
-          base_dir: 'backend'
-          check: 'zpretty'
+        - name: Run tests
+          run: make test
 
-  tests:
+  coverage:
     runs-on: ubuntu-latest
     needs:
-      - meta
-    defaults:
-      run:
-        working-directory: ./backend
-
+      - test
     steps:
-      - uses: actions/checkout@v4
+        - name: Checkout
+          uses: actions/checkout@v4
 
-      - name: Setup Plone ${{ needs.meta.outputs.PLONE_VERSION }} with Python ${{ env.PYTHON_VERSION }}
-        uses: plone/setup-plone@v2.0.0
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
-          plone-version: ${{ needs.meta.outputs.PLONE_VERSION }}
+        - name: Install the latest version of uv
+          uses: astral-sh/setup-uv@v5
+          with:
+            python-version: ${{ inputs.python-version }}
+            enable-cache: false
 
-      - name: Install package
-        run: |
-          pip install mxdev
-          mxdev -c mx.ini
-          pip install -r requirements-mxdev.txt
+        - name: Restore uv cache
+          uses: actions/cache@v4
+          with:
+            path: /tmp/.uv-cache
+            key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
+            restore-keys: |
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}-${{ hashFiles('pyproject.toml') }}
+              uv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.plone-version }}
 
-      - name: Run tests
-        run: |
-          pytest --disable-warnings src/sneridagh_dev/tests
+        - name: Install Plone and package
+          run: make install
+
+        - name: Run tests
+          run: make test-coverage
+
+        - name: Report Coverage
+          run: |
+            echo "# Coverage Report" >> $GITHUB_STEP_SUMMARY
+            echo "$(uv run coverage report --format markdown)" >> $GITHUB_STEP_SUMMARY
 
   release:
     runs-on: ubuntu-latest
     needs:
-      - black
-      - flake8
-      - isort
-      - zpretty
-      - tests
+      - lint
+      - coverage
     permissions:
       contents: read
       packages: write
@@ -121,9 +159,9 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: |
-            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}
+            ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}:latest
+            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:${{ inputs.base-tag }}
           flavor:
             latest=false
           tags: |
@@ -145,11 +183,13 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build and push
-        uses: docker/build-push-action@v4
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64
-          context: backend
+          context: backend/
           file: backend/Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            PLONE_VERSION=${{ inputs.plone-version }}
